>D
;*****
; for / fuer eHZ HW8E
;*****
;After selecting a script, be sure to activate it and reboot!
;Nachdem auswaehlen eines Scripts, unbedingt dieses aktivieren und einen Neustart durchfuehren!
>B
=>sensor53 r
;Interval fuer das Senden von Daten auf 10Sekunden / Set teleperiod to 10sec  
tper=10
>M 1
+1,14,s,0,9600,Strom
1,77070100010801ff@1000,Gesamt Verbrauch,KWh,Total_in,3
1,770701000f0700ff@1,Aktueller Verbrauch,W,Power_cur,0
#
