>D
;*****
; for / fuer Landis+Gyr E320
;*****
;After selecting a script, be sure to activate it and reboot!
;Nachdem auswaehlen eines Scripts, unbedingt dieses aktivieren und einen Neustart durchfuehren!
>B
=>sensor53 r
;Interval fuer das Senden von Daten auf 10Sekunden / Set teleperiod to 10sec  
tper=10
>M 1
+1,14,s,0,9600,SML
1,77070100010800ff@1000,Verbrauch Bezug,kWh,Total_in,4
1,77070100020800ff@1000,Einspeisung,kWh,Total_out,4
1,77070100100700ff#W,Leistung,W,Power,2
1,77070100600100ff@#,Zählernummer,,Meter_id,0
#
